module GraphQL
  module Coverage
    module Errors
      class SchemaMismatch < StandardError
        def initialize: (expected: untyped, got: untyped) -> void
      end

      class UncoveredFields < StandardError
      end
    end
  end
end
