AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - spec/exe/graphql-coverage_spec.rb
