#!/usr/bin/env ruby

$LOAD_PATH << File.join(__dir__, "../lib")

require 'graphql/coverage'
require 'graphql/coverage/cli'

exit GraphQL::Coverage::CLI.new(stdout: $stdout, stderr: $stderr).run(ARGV)
